version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: python writecoach/api.py
    
  streamlit:
    build: .
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: cd writecoach && streamlit run app.py --server.port 8501 --server.address 0.0.0.0